// Generated by LiveScript 1.6.0
(function(){
  'use strict';
  var exec, async, testSucceeded, testFailed;
  exec = require('child_process').exec;
  async = require('async');
  testSucceeded = function(done){
    console.log('> grunt zshlint:succeeded');
    return exec('grunt zshlint:succeeded', function(err, stdout, stderr){
      if (stdout) {
        process.stdout.write(stdout);
      }
      if (stderr) {
        process.stdout.write(stderr);
      }
      return done(err);
    });
  };
  testFailed = function(done){
    console.log('> grunt zshlint:failed');
    return exec('grunt zshlint:failed', function(err, stdout, stderr){
      if (stdout) {
        process.stdout.write(stdout);
      }
      if (stderr) {
        process.stdout.write(stderr);
      }
      if (err) {
        return done('grunt succeeded');
      }
      return done();
    });
  };
  module.exports = function(grunt){
    return grunt.registerTask('zshlint-test', function(){
      var done;
      done = this.async();
      return async.parallel([testSucceeded, testFailed], function(err){
        if (err) {
          grunt.log.error(err);
        }
        return done(err);
      });
    });
  };
}).call(this);
