// Generated by LiveScript 1.6.0
(function(){
  'use strict';
  module.exports = function(grunt){
    return grunt.config.set('zshlint', {
      succeeded: {
        src: ['test/succeeded.zsh']
      },
      failed: {
        src: ['test/failed.zsh']
      }
    });
  };
}).call(this);
